### ISSUE TITLE
NVidia and DKMS

### ISSUE THREAD

**Issue by rabinnh** [rykdesjardins/fix-UX6404VI-audio-linux#4]
I successfully compiled and ran the kernel, but NVidia modules didn't load.  

I think you need to trigger DKMS after "sudo make install" and "sudo make modules_install".  Something like:

sudo /usr/lib/dkms/dkms_autoinstaller start 6.5.13

Make sure that the kernel headers are copied to the correct location for your distro before running.

Still working on it though, because I get: *** No rule to make target '/Kbuild'. Stop.

So at this point, I'm trading audio for being able to use my NVidia 4070 - not a good trade.

**Comment by dirkjanvanvliet** [comment]
Is this confirmed for all UX6404 devices? I'm eager to use some Linux distro on my UX6404, but I would like to use both audio and my Nvidia 4070...

**Comment by rabinnh** [comment]
I stopped working on it because my understanding is that  kernel 6.7 addresses the audio issue. It's supposed to be released on January 7th so I was waiting to test it before proceeding with any more work.

**Comment by dirkjanvanvliet** [comment]
Good to hear it should be fixed in 6.7. I'll give it a try when it's released, thanks!

**Comment by rykdesjardins** [comment]
Surprisingly enough, on a clean Ubuntu install, using the [nvidia drivers from the installer](https://www.nvidia.com/download/driverResults.aspx/216728/en-us/) released on December 7th allowed using both the GPU and audio. 

![image](https://github.com/rykdesjardins/fix-UX6404VI-audio-linux/assets/14999498/87105e37-cd02-4691-9c4b-aabb953cb582)

Installed everything in the following order : 
- clean ubuntu install, no third party drivers pre-installed
- patched audio drivers
- patched kernel
- updated grub
- installed Nvidia drivers from installer

Sorry I can't be of more help here-- I have no idea why this worked first try ; might be the post-install routine? 

Hopefully the 6.7 minor will have a definitive fix for this.

**Comment by rabinnh** [comment]
Very likely.  I tried on an existing system.  Also, I use CUDA for PyTorch and other tools which means that my NVidia installation is way more complicated than just the graphics driver. 

Either way, thank you for your great work.  It was a fun experiment anyway ;-)

**Comment by jemlinus** [comment]
Since 6.7 has been release, I wonder if this issue has been addressed.  I'm away to check for myself, but I wonder.

**Comment by rykdesjardins** [comment]
![image](https://github.com/rykdesjardins/fix-UX6404VI-audio-linux/assets/14999498/7550e23e-6836-46b7-804b-16dce88ae7f0)

Welp. It works. 

Audio works (way louder, too) and graphics card functions properly with and without external display. 

It's still not stable so I expect some ups and downs, but for now everything seems to be smooth sailing.

**Comment by rabinnh** [comment]
I installed the Ubuntu built version from their mainline build area (https://kernel.ubuntu.com/mainline/?C=N;O=D).  The kernel is still unsigned and the headers wouldn't install due to a libc dependency mismatch.

That said, I booted it just to test and heard the bongo (which I will turn off once the system is stable).  In the meanwhile, I'll uninstall and wait for the official ubuntu build.

**Comment by jemlinus** [comment]
![Kernel_6 7_UX6404VI](https://github.com/rykdesjardins/fix-UX6404VI-audio-linux/assets/141101605/b4aec746-a4cb-41fb-9ac4-323d2c7b0676)
Awesome.

**Comment by jemlinus** [comment]
I did bare metal install on my UX6404VI with Nobara 39 because they updated the kernel to 6.7 yesterday.  The speaker output works for a bit and then goes silent with very low volume.  And headphone jack still not working. 

The setting shows Raptor Lake output instead of Realtek.  I think we might have to wait a little longer to this machine to work properly.

**Comment by dirkjanvanvliet** [comment]
I'm running Manjaro KDE and after installing some updates today, kernel 6.7 came available. I have to note though that during the updates, I saw a audio device change. But audio was not working after updating. Then I installed 6.7, and I'm afraid I got the same result als jemlinus. Audio worked for like a second, but it was a bit garbled, and after that it stopped and there was no audio anymore. Sad.

**Comment by dirkjanvanvliet** [comment]
I don´t know what happened, but on my installation it suddenly works. What I did was:

1. Reinstalled Manjaro KDE (for other reasons, not this problem)
2. Updated to kernel 6.7 (heck, why not)
3. Updated all available updates

And after a few days I noticed that sound was suddenly working. I rebooted a few times, waited a few days, but the sound still works. It is not garbled or anything and also my Nvidia graphics card works as it should. 

Don´t know what made it work, maybe an update?

P.s. I didn´t do any of the steps mentioned by @rykdesjardins.

**Comment by jemlinus** [comment]
The current 6.7.0-204 version kernel still only works for a couple of second and then goes silent(Nobara 39).  There were Cirrus drivers updated recently so that might have helped working with the other distros.  I'm waiting for 6.7.3 kernel update now.  Cross my fingers.  I definitely won't buy anymore Asus laptops.  What a terrible company with Linux support.  All my Lenovo and Dell laptops never had single issue with them even the day one I bought them.

**Comment by dirkjanvanvliet** [comment]
Waiting a few days was still too soon to call it fixed. The problem sometimes comes back, and then there is no sound. And sometimes it works.

**Comment by jemlinus** [comment]
Fedora with 6.7.3 kernel is still not working.  I gave up.  I'm going to use this as a Windows machine only.   Going back to Lenovo for mobile Linux machine.  Good luck everyone.

**Comment by rabinnh** [comment]
For anyone still following this thread, my sound is now working.

* I'm on Ubuntu, so first I had to update to 23.10 because I needed the 2.38 version of libc6 in order to install kernel 6.7
* Then I downloaded all the mainline kernel deb packages for 6.7.5
* I then moved them into their own directory and ran "sudo dpkg -i *.deb" which successfully installed the kernel
* On reboot the sound worked, but once I went into the Sound applet and fiddled around while the mic still worked, output did not.
* I installed pavucontrol (sudo apt-get install pavucontrol)
* In pavucntrol set the following:
* * Go to "Configuration".  Set sof-hda-dsp to "Pro Audio".
* * Under "Input Devices" when you speak you should see the meter react.
Works for me.
